const {
  SIG,
  TYPE,
  VERSION,
  AUTHOR
} = require('@tradle/constants')

const HEADER_PROPS = [SIG]
const REQUIRED_IDENTITY_PROPS = HEADER_PROPS.concat([
  TYPE,
  VERSION,
])

const REQUIRED_NON_IDENTITY_PROPS = REQUIRED_IDENTITY_PROPS.concat(AUTHOR)

module.exports = {
  HEADER_PROPS,
  REQUIRED_IDENTITY_PROPS,
  REQUIRED_NON_IDENTITY_PROPS
}
